import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './utils/NavBar'
import Footer from './utils/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Restaurant Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
